service: articles-dispenser-api

provider:
  name: aws
  runtime: nodejs12.x
  environment:    
    CONSUMER_KEY: "SECRET"
    CLIENT_URL: "URL"

plugins:  
  - serverless-offline

functions:
  getRequestToken:
    handler: handler.getRequestToken
    events:
      - http:
          path: getRequestToken
          method: get
  getAccessToken:
    handler: handler.getAccessToken
    events:
      - http:
          path: getAccessToken
          method: get
          request: 
            parameters:
              querystrings:
                url: true
  getArticles:
    handler: handler.getArticles
    events:
      - http:
          path: getArticles
          method: get
          request: 
            parameters:
              querystrings:
                url: true